language: python
python:
  - "2.7.12"
  - "3.5"
install: 
  - pip install --upgrade pip
  - python --version
  - pip --version
  - pip install -r requirements.txt
# command to run tests
script: python setup.py test
os:
  - linux
# Need trusty+ for tensorflow
dist: trusty
